---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      volumes:
        - name: db
          hostPath:
            path: /tmp/ganache-db
            type: DirectoryOrCreate
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          name: ganache
          image: trufflesuite/ganache-cli
          command: ["node /app/ganache-core.docker.cli.js --db /var/lib/ganache"]
          volumeMounts:
            - name: db
              mountPath: /var/lib/ganache
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
spec:
  selector:
    app: ganache
  ports:
    - name: ganache
      port: 80
      targetPort: 8545
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ganache.asgame.xyz
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: cf
    domains:
      - main: asgame.xyz
        sans:
          - "*.asgame.xyz"
  routes:
    - match: Host(`ganache.asgame.xyz`)
      kind: Rule
      services:
        - name: ganache
          port: 80
